version: "3"

services:
  app:
    build: ./Dockerfile
    volumes: 
      - ./:/var/www/html
    ports:
      - 8080:80
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - DATABASE=database
